<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Identity\Migrations\20250710132037_UpdateV02.Designer.cs" />
    <Compile Remove="Identity\Migrations\20250710132403_UpdateDb.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\DataSeed\studentattendance.json~RFde747e7.TMP" />
    <None Remove="Data\DataSeed\studentattendance.json~RFe15bb23.TMP" />
    <None Remove="Data\DataSeed\studentcourse.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
   
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AttendanceApi.Core\AttendanceApi.Core.csproj" />
  </ItemGroup>

</Project>
